/**
 * Program latihan yang disepakati:
 * A = Dada + Bicep (+ bahu depan/samping), B = Back + Tricep (+ bahu belakang),
 * C = Lower (ramah lutut). Core 5–8 menit di akhir tiap sesi.
 *
 * Tiap hari tersusun dari slot dengan fungsi tetap; tiap slot punya 2–3 kandidat
 * gerakan (yang pertama = gerakan default ⭐). Core diambil dari satu kolam bersama.
 */
import type { DayType, ExerciseDef, SlotDef, TrainingDay } from './types';

type RawExercise = Omit<ExerciseDef, 'primary' | 'optional'>;

/** Gerakan asli (⭐) — id tetap sama agar riwayat & progres lama tetap berlaku. */
const ORIGINAL: RawExercise[] = [
  // ───────────── Hari A ─────────────
  {
    id: 'floor-press',
    name: 'DB Floor Press',
    slot: 'A1',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellPair',
    sets: 3,
    repMin: 8,
    repMax: 12,
    restSec: 120,
    calibrationLoad: 6.4,
    load: { bahu: 'ringan', siku: 'ringan', 'pergelangan-tangan': 'ringan' },
    muscles: 'Dada, tricep, bahu depan',
    cues: [
      'Berbaring di lantai, lutut ditekuk, telapak kaki menapak.',
      'Dumbel di atas dada, telapak tangan menghadap kaki.',
      'Turunkan perlahan sampai lengan atas menyentuh lantai (siku ±45° dari badan).',
      'Dorong naik sambil membuang napas, jangan sampai dumbel beradu.',
    ],
    mistakes: ['Siku melebar 90° (bahu tertekan)', 'Lengan dibanting ke lantai', 'Pinggul terangkat'],
    youtubeQuery: 'dumbbell floor press form',
  },
  {
    id: 'push-up',
    name: 'Push-up',
    slot: 'A2',
    block: 'main',
    kind: 'reps',
    sets: 2,
    repMin: 6,
    repMax: 15,
    restSec: 90,
    variants: ['Incline Push-up (tangan di kursi)', 'Push-up di lantai'],
    load: { 'pergelangan-tangan': 'sedang', bahu: 'ringan', siku: 'ringan' },
    muscles: 'Dada, tricep, core',
    cues: [
      'Tangan sedikit lebih lebar dari bahu.',
      'Badan lurus dari kepala sampai tumit (kencangkan perut & bokong).',
      'Turunkan dada sampai hampir menyentuh kursi/lantai, lalu dorong naik.',
    ],
    mistakes: ['Pinggul turun/melengkung', 'Kepala maju duluan', 'Gerakan setengah'],
    youtubeQuery: 'incline push up proper form',
  },
  {
    id: 'seated-ohp',
    name: 'Seated DB Overhead Press',
    slot: 'A3',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellPair',
    sets: 3,
    repMin: 8,
    repMax: 12,
    restSec: 120,
    calibrationLoad: 5.4,
    load: { bahu: 'berat', siku: 'ringan', 'punggung-bawah': 'ringan' },
    muscles: 'Bahu depan & samping, tricep',
    cues: [
      'Duduk tegak di kursi, punggung menempel sandaran kalau ada.',
      'Dumbel di samping telinga, siku sedikit di depan badan.',
      'Dorong lurus ke atas sampai lengan hampir lurus, turunkan terkontrol.',
    ],
    mistakes: ['Punggung bawah melengkung berlebihan', 'Leher menjulur ke depan', 'Siku mengunci keras'],
    youtubeQuery: 'seated dumbbell shoulder press form',
  },
  {
    id: 'lateral-raise',
    name: 'DB Lateral Raise',
    slot: 'A4',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellPair',
    sets: 2,
    repMin: 12,
    repMax: 20,
    restSec: 60,
    calibrationLoad: 2.9,
    load: { bahu: 'sedang' },
    muscles: 'Bahu samping',
    cues: [
      'Berdiri, dumbel di samping paha, siku sedikit ditekuk.',
      'Angkat ke samping sampai setinggi bahu — pimpin dengan siku.',
      'Turunkan perlahan (2 detik).',
    ],
    mistakes: ['Mengayun dengan badan', 'Mengangkat melewati bahu', 'Bahu naik ke telinga'],
    youtubeQuery: 'dumbbell lateral raise form',
  },
  {
    id: 'barbell-curl',
    name: 'Barbell Curl',
    slot: 'A5',
    block: 'main',
    kind: 'weighted',
    loadMode: 'barbell',
    sets: 3,
    repMin: 8,
    repMax: 12,
    restSec: 75,
    calibrationLoad: 10.85,
    load: { siku: 'sedang', 'pergelangan-tangan': 'sedang' },
    muscles: 'Bicep',
    cues: [
      'Berdiri, pegang barbel selebar bahu, telapak menghadap depan.',
      'Siku menempel di samping badan.',
      'Tekuk siku sampai barbel di depan bahu, turunkan perlahan.',
    ],
    mistakes: ['Mengayun pinggul', 'Siku maju ke depan', 'Turun terlalu cepat'],
    youtubeQuery: 'barbell curl proper form',
  },
  {
    id: 'hammer-curl',
    name: 'DB Hammer Curl',
    slot: 'A6',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellPair',
    sets: 2,
    repMin: 10,
    repMax: 15,
    restSec: 60,
    calibrationLoad: 5.4,
    load: { siku: 'ringan', 'pergelangan-tangan': 'ringan' },
    muscles: 'Bicep, brachialis, lengan bawah',
    cues: ['Pegang dumbel dengan telapak saling berhadapan (seperti memegang palu).', 'Tekuk siku tanpa memutar pergelangan.', 'Turunkan perlahan.'],
    mistakes: ['Mengayun', 'Siku bergeser maju'],
    youtubeQuery: 'dumbbell hammer curl form',
  },
  // ───────────── Hari B ─────────────
  {
    id: 'bent-over-row',
    name: 'Barbell Bent-over Row',
    slot: 'B1',
    block: 'main',
    kind: 'weighted',
    loadMode: 'barbell',
    sets: 3,
    repMin: 8,
    repMax: 12,
    restSec: 120,
    calibrationLoad: 16.85,
    load: { 'punggung-bawah': 'sedang', siku: 'ringan', 'pergelangan-tangan': 'ringan' },
    muscles: 'Punggung atas, lat, bicep',
    cues: [
      'Lutut sedikit ditekuk, dorong pinggul ke belakang sampai badan ±45°.',
      'Punggung lurus (netral), barbel menggantung di bawah bahu.',
      'Tarik barbel ke perut bawah, rapatkan tulang belikat.',
      'Turunkan terkontrol tanpa mengubah posisi badan.',
    ],
    mistakes: ['Punggung membungkuk', 'Badan naik-turun mengayun', 'Menarik ke dada'],
    youtubeQuery: 'barbell bent over row form',
  },
  {
    id: 'one-arm-row',
    name: 'One-arm DB Row',
    slot: 'B2',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellSingle',
    sets: 3,
    repMin: 10,
    repMax: 15,
    perSide: true,
    restSec: 90,
    calibrationLoad: 9.4,
    load: { siku: 'ringan', 'punggung-bawah': 'ringan', bahu: 'ringan' },
    muscles: 'Lat, punggung tengah',
    cues: [
      'Satu tangan bertumpu di kursi, kaki selebar bahu, punggung datar.',
      'Dumbel menggantung lurus di bawah bahu.',
      'Tarik siku ke arah pinggul, tahan sebentar, turunkan penuh.',
    ],
    mistakes: ['Badan berputar', 'Menarik dengan bicep saja', 'Punggung membulat'],
    youtubeQuery: 'one arm dumbbell row form',
  },
  {
    id: 'rear-delt-fly',
    name: 'DB Rear Delt Fly',
    slot: 'B3',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellPair',
    sets: 2,
    repMin: 12,
    repMax: 20,
    restSec: 60,
    calibrationLoad: 2.9,
    load: { bahu: 'ringan', 'punggung-bawah': 'ringan' },
    muscles: 'Bahu belakang, punggung atas',
    cues: [
      'Badan membungkuk ±45–60°, punggung lurus, siku sedikit ditekuk.',
      'Buka lengan ke samping seperti sayap sampai sejajar badan.',
      'Turunkan perlahan.',
    ],
    mistakes: ['Memakai beban terlalu berat', 'Menarik dengan punggung (rowing)', 'Leher tegang'],
    youtubeQuery: 'bent over dumbbell rear delt fly form',
  },
  {
    id: 'lying-tricep-ext',
    name: 'DB Lying Triceps Extension',
    slot: 'B4',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellPair',
    sets: 3,
    repMin: 10,
    repMax: 15,
    restSec: 75,
    calibrationLoad: 4.4,
    load: { siku: 'sedang' },
    muscles: 'Tricep',
    cues: [
      'Berbaring di lantai, lengan lurus ke atas, telapak saling berhadapan.',
      'Tekuk siku saja — dumbel turun ke samping kepala.',
      'Luruskan kembali tanpa menggerakkan lengan atas.',
    ],
    mistakes: ['Siku melebar', 'Lengan atas ikut bergerak', 'Turun terlalu cepat dekat kepala'],
    youtubeQuery: 'dumbbell skull crusher floor form',
  },
  {
    id: 'overhead-tricep-ext',
    name: 'DB Overhead Triceps Extension',
    slot: 'B5',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellSingle',
    sets: 2,
    repMin: 10,
    repMax: 15,
    restSec: 60,
    calibrationLoad: 6.4,
    load: { siku: 'sedang', bahu: 'sedang' },
    muscles: 'Tricep (kepala panjang)',
    cues: [
      'Duduk tegak, pegang satu dumbel dengan dua tangan di atas kepala.',
      'Turunkan dumbel ke belakang kepala dengan menekuk siku.',
      'Luruskan kembali, siku tetap menunjuk ke depan/atas.',
    ],
    mistakes: ['Punggung melengkung', 'Siku terbuka lebar'],
    youtubeQuery: 'seated dumbbell overhead triceps extension form',
  },
  {
    id: 'close-grip-push-up',
    name: 'Close-grip Push-up',
    slot: 'B6',
    block: 'main',
    kind: 'reps',
    sets: 2,
    repMin: 5,
    repMax: 15,
    restSec: 60,
    variants: ['Close-grip Incline Push-up (tangan di kursi)', 'Close-grip Push-up di lantai'],
    load: { 'pergelangan-tangan': 'sedang', siku: 'sedang' },
    muscles: 'Tricep, dada',
    cues: ['Tangan selebar bahu atau sedikit lebih sempit.', 'Siku menempel ke badan saat turun.', 'Badan tetap lurus.'],
    mistakes: ['Siku melebar', 'Pinggul turun'],
    youtubeQuery: 'close grip incline push up form',
  },
  // ───────────── Hari C ─────────────
  {
    id: 'goblet-box-squat',
    name: 'Goblet Box Squat ke Kursi',
    slot: 'C1',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellSingle',
    sets: 3,
    repMin: 8,
    repMax: 12,
    restSec: 120,
    lowerBody: true,
    calibrationLoad: 9.4,
    kneeNote: 'Lutut sedang nyeri: pakai kursi lebih tinggi (tambah bantal) agar jongkok lebih dangkal.',
    load: { lutut: 'ringan', pinggul: 'ringan' },
    muscles: 'Paha depan, bokong',
    cues: [
      'Pegang satu dumbel vertikal di depan dada.',
      'Kaki selebar bahu, ujung kaki sedikit keluar, kursi di belakang.',
      'Dorong pinggul ke belakang, turun sampai bokong menyentuh kursi (jangan duduk penuh).',
      'Dorong lantai dengan seluruh telapak untuk berdiri.',
    ],
    mistakes: ['Lutut masuk ke dalam', 'Tumit terangkat', 'Menjatuhkan diri ke kursi'],
    youtubeQuery: 'goblet box squat form',
  },
  {
    id: 'rdl',
    name: 'Barbell Romanian Deadlift',
    slot: 'C2',
    block: 'main',
    kind: 'weighted',
    loadMode: 'barbell',
    sets: 3,
    repMin: 8,
    repMax: 12,
    restSec: 120,
    lowerBody: true,
    calibrationLoad: 19.85,
    load: { 'punggung-bawah': 'sedang', pinggul: 'ringan' },
    muscles: 'Hamstring, bokong, punggung bawah',
    cues: [
      'Berdiri, barbel di depan paha, lutut sedikit ditekuk (tetap).',
      'Dorong pinggul ke belakang, barbel meluncur dekat paha & tulang kering.',
      'Turun sampai terasa tarikan di paha belakang (±bawah lutut), punggung tetap lurus.',
      'Dorong pinggul ke depan untuk berdiri.',
    ],
    mistakes: ['Punggung membulat', 'Barbel menjauh dari kaki', 'Jongkok seperti squat'],
    youtubeQuery: 'barbell romanian deadlift form',
  },
  {
    id: 'hip-thrust',
    name: 'Barbell Glute Bridge / Hip Thrust (lantai)',
    slot: 'C3',
    block: 'main',
    kind: 'weighted',
    loadMode: 'barbell',
    sets: 3,
    repMin: 10,
    repMax: 15,
    restSec: 90,
    lowerBody: true,
    calibrationLoad: 19.85,
    load: { pinggul: 'sedang' },
    muscles: 'Bokong, hamstring',
    cues: [
      'Berbaring, lutut ditekuk, barbel di lipatan pinggul (alasi handuk).',
      'Dorong lewat tumit, angkat pinggul sampai badan lurus dari bahu ke lutut.',
      'Kencangkan bokong 1 detik di atas, turunkan perlahan.',
    ],
    mistakes: ['Punggung bawah melengkung di atas', 'Mendorong dengan ujung kaki'],
    youtubeQuery: 'barbell glute bridge floor form',
  },
  {
    id: 'step-up',
    name: 'Step-up Rendah',
    slot: 'C4',
    block: 'main',
    kind: 'reps',
    sets: 2,
    repMin: 8,
    repMax: 12,
    perSide: true,
    restSec: 75,
    lowerBody: true,
    variants: ['Step-up anak tangga (tanpa beban)', 'Step-up anak tangga sambil pegang dumbel ringan'],
    load: { lutut: 'sedang', engkel: 'ringan' },
    muscles: 'Paha depan, bokong, keseimbangan',
    cues: [
      'Seluruh telapak kaki depan di atas anak tangga.',
      'Naik dengan mendorong kaki depan, kaki belakang hanya mengikuti.',
      'Turun perlahan, lutut searah jari kaki.',
    ],
    mistakes: ['Melompat dengan kaki belakang', 'Lutut masuk ke dalam'],
    youtubeQuery: 'low step up exercise form knee friendly',
  },
  {
    id: 'calf-raise',
    name: 'Standing Calf Raise (DB)',
    slot: 'C5',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellPair',
    sets: 3,
    repMin: 12,
    repMax: 20,
    restSec: 60,
    calibrationLoad: 7.9,
    load: { engkel: 'sedang', 'tulang-kering': 'ringan' },
    muscles: 'Betis',
    cues: ['Pegang dumbel di samping badan (boleh satu tangan berpegangan ke dinding).', 'Jinjit setinggi mungkin, tahan 1 detik.', 'Turunkan tumit perlahan.'],
    mistakes: ['Memantul cepat', 'Lutut ditekuk-tekuk'],
    youtubeQuery: 'dumbbell standing calf raise form',
  },
  // ───────────── Core ─────────────
  {
    id: 'plank',
    name: 'Plank',
    slot: 'core',
    block: 'core',
    coreType: 'anti',
    kind: 'timed',
    sets: 2,
    repMin: 20,
    repMax: 60,
    restSec: 45,
    load: { bahu: 'ringan', 'punggung-bawah': 'ringan' },
    muscles: 'Core',
    cues: ['Bertumpu pada lengan bawah dan ujung kaki.', 'Badan lurus, kencangkan perut & bokong.', 'Napas tetap jalan.'],
    mistakes: ['Pinggul turun', 'Pinggul terlalu tinggi'],
    youtubeQuery: 'plank proper form',
  },
  {
    id: 'dead-bug',
    name: 'Dead Bug',
    slot: 'core',
    block: 'core',
    coreType: 'anti',
    kind: 'reps',
    sets: 2,
    repMin: 6,
    repMax: 12,
    perSide: true,
    restSec: 45,
    load: { 'punggung-bawah': 'ringan' },
    muscles: 'Core (anti-ekstensi)',
    cues: ['Berbaring, tangan lurus ke atas, lutut 90°.', 'Turunkan tangan kanan & kaki kiri bersamaan, punggung bawah tetap menempel lantai.', 'Kembali, ganti sisi.'],
    mistakes: ['Punggung bawah terangkat', 'Terlalu cepat'],
    youtubeQuery: 'dead bug exercise form',
  },
  {
    id: 'side-plank',
    name: 'Side Plank',
    slot: 'core',
    block: 'core',
    coreType: 'other',
    kind: 'timed',
    sets: 2,
    repMin: 15,
    repMax: 45,
    perSide: true,
    restSec: 30,
    load: { bahu: 'sedang', 'punggung-bawah': 'ringan' },
    muscles: 'Core samping (oblique)',
    cues: ['Bertumpu pada satu lengan bawah, siku di bawah bahu.', 'Badan lurus menyamping; versi mudah: lutut ditekuk.', 'Angkat pinggul.'],
    mistakes: ['Pinggul turun', 'Badan condong ke depan'],
    youtubeQuery: 'side plank form beginner',
  },
  {
    id: 'bird-dog',
    name: 'Bird Dog',
    slot: 'core',
    block: 'core',
    coreType: 'anti',
    kind: 'reps',
    sets: 2,
    repMin: 6,
    repMax: 10,
    perSide: true,
    restSec: 30,
    load: { 'pergelangan-tangan': 'ringan', 'punggung-bawah': 'ringan' },
    muscles: 'Core, punggung bawah, bokong',
    cues: ['Posisi merangkak, tangan di bawah bahu, lutut di bawah pinggul.', 'Luruskan tangan kanan & kaki kiri, tahan 2 detik.', 'Kembali, ganti sisi.'],
    mistakes: ['Pinggul berputar', 'Punggung melengkung'],
    youtubeQuery: 'bird dog exercise form',
  },
  {
    id: 'glute-bridge-hold',
    name: 'Glute Bridge Hold',
    slot: 'core',
    block: 'core',
    coreType: 'other',
    kind: 'timed',
    sets: 2,
    repMin: 20,
    repMax: 60,
    restSec: 30,
    load: { pinggul: 'ringan' },
    muscles: 'Bokong, core',
    cues: ['Berbaring, lutut ditekuk.', 'Angkat pinggul sampai lurus dari bahu ke lutut, tahan.', 'Kencangkan bokong, jangan melengkungkan punggung.'],
    mistakes: ['Punggung melengkung', 'Pinggul turun perlahan'],
    youtubeQuery: 'glute bridge hold form',
  },
  {
    id: 'hollow-hold',
    name: 'Hollow Hold (versi mudah)',
    slot: 'core',
    block: 'core',
    coreType: 'anti',
    kind: 'timed',
    sets: 2,
    repMin: 10,
    repMax: 30,
    restSec: 30,
    load: { 'punggung-bawah': 'ringan', leher: 'ringan' },
    muscles: 'Core depan',
    cues: ['Berbaring, punggung bawah ditekan ke lantai.', 'Angkat bahu & kaki sedikit, lutut boleh ditekuk (versi mudah).', 'Tahan tanpa punggung bawah terangkat.'],
    mistakes: ['Punggung bawah terangkat dari lantai', 'Menahan napas'],
    youtubeQuery: 'hollow hold beginner tuck',
  },
];

/** Gerakan tambahan bank (alat: barbel/dumbel, kursi, lantai, tembok, satu anak tangga). */
const BANK: RawExercise[] = [
  // ───────────── Hari A ─────────────
  {
    id: 'barbell-floor-press',
    name: 'Barbell Floor Press',
    slot: 'A1',
    block: 'main',
    kind: 'weighted',
    loadMode: 'barbell',
    sets: 3,
    repMin: 8,
    repMax: 12,
    restSec: 120,
    calibrationLoad: 16.85,
    siblings: [{ id: 'floor-press', ratio: 1.8 }],
    load: { bahu: 'sedang', 'pergelangan-tangan': 'sedang', siku: 'ringan' },
    muscles: 'Dada, tricep, bahu depan',
    cues: [
      'Duduk di lantai dengan barbel di pangkuan, lalu berbaring dan gulingkan barbel ke atas dada.',
      'Pegang sedikit lebih lebar dari bahu, lutut ditekuk, telapak kaki menapak.',
      'Turunkan sampai lengan atas menyentuh lantai, jeda sebentar.',
      'Dorong lurus ke atas di atas dada.',
    ],
    mistakes: ['Siku melebar 90°', 'Lengan dibanting ke lantai', 'Barbel turun ke leher'],
    youtubeQuery: 'barbell floor press form',
  },
  {
    id: 'db-squeeze-press',
    name: 'DB Squeeze Press (lantai)',
    slot: 'A1',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellPair',
    sets: 3,
    repMin: 10,
    repMax: 15,
    restSec: 90,
    calibrationLoad: 5.4,
    siblings: [{ id: 'floor-press', ratio: 0.8 }],
    load: { bahu: 'ringan', siku: 'ringan', 'pergelangan-tangan': 'ringan' },
    muscles: 'Dada bagian dalam, tricep',
    cues: [
      'Berbaring di lantai, dua dumbel saling menempel di atas dada, telapak saling berhadapan.',
      'Tekan kedua dumbel satu sama lain sepanjang gerakan.',
      'Turunkan sampai lengan atas menyentuh lantai, dorong naik sambil tetap menekan.',
    ],
    mistakes: ['Dumbel terpisah', 'Siku melebar', 'Terlalu cepat'],
    youtubeQuery: 'dumbbell squeeze press floor form',
  },
  {
    id: 'db-floor-fly',
    name: 'DB Floor Fly',
    slot: 'A2',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellPair',
    sets: 3,
    repMin: 10,
    repMax: 15,
    restSec: 75,
    calibrationLoad: 2.9,
    siblings: [{ id: 'floor-press', ratio: 0.45 }],
    load: { bahu: 'sedang', siku: 'ringan' },
    muscles: 'Dada',
    cues: [
      'Berbaring di lantai, dumbel di atas dada, telapak saling berhadapan, siku sedikit ditekuk.',
      'Buka lengan ke samping seperti memeluk pohon sampai lengan atas menyentuh lantai.',
      'Rapatkan kembali di atas dada dengan meremas dada.',
    ],
    mistakes: ['Lengan diluruskan penuh', 'Beban terlalu berat', 'Lengan dibanting ke lantai'],
    youtubeQuery: 'dumbbell floor fly form',
  },
  {
    id: 'arnold-press',
    name: 'Seated Arnold Press',
    slot: 'A3',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellPair',
    sets: 3,
    repMin: 8,
    repMax: 12,
    restSec: 120,
    calibrationLoad: 4.4,
    siblings: [{ id: 'seated-ohp', ratio: 0.85 }],
    load: { bahu: 'berat', siku: 'ringan' },
    muscles: 'Bahu depan & samping, tricep',
    cues: [
      'Duduk tegak di kursi, dumbel di depan bahu dengan telapak menghadap badan.',
      'Sambil mendorong ke atas, putar telapak sampai menghadap depan.',
      'Turunkan sambil memutar kembali ke posisi awal.',
    ],
    mistakes: ['Punggung melengkung', 'Putaran terburu-buru', 'Siku mengunci keras'],
    youtubeQuery: 'seated arnold press form',
  },
  {
    id: 'standing-barbell-press',
    name: 'Standing Barbell Press',
    slot: 'A3',
    block: 'main',
    kind: 'weighted',
    loadMode: 'barbell',
    sets: 3,
    repMin: 8,
    repMax: 12,
    restSec: 120,
    calibrationLoad: 10.85,
    siblings: [{ id: 'seated-ohp', ratio: 1.6 }],
    load: { bahu: 'berat', 'punggung-bawah': 'sedang', 'pergelangan-tangan': 'sedang' },
    muscles: 'Bahu, tricep, core',
    cues: [
      'Berdiri selebar pinggul, barbel di depan bahu, pegangan sedikit lebih lebar dari bahu.',
      'Kencangkan perut & bokong, tarik dagu sedikit ke belakang.',
      'Dorong barbel lurus ke atas sampai di atas kepala, lalu turunkan ke depan bahu.',
    ],
    mistakes: ['Punggung bawah melengkung', 'Mendorong dengan lutut', 'Barbel jauh di depan wajah'],
    youtubeQuery: 'standing barbell overhead press form',
  },
  {
    id: 'lean-away-lateral-raise',
    name: 'Lean-away Lateral Raise',
    slot: 'A4',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellSingle',
    sets: 2,
    repMin: 12,
    repMax: 20,
    perSide: true,
    restSec: 45,
    calibrationLoad: 2.9,
    siblings: [{ id: 'lateral-raise', ratio: 1 }],
    load: { bahu: 'sedang' },
    muscles: 'Bahu samping',
    cues: [
      'Berdiri menyamping di dekat tembok, pegang tembok dengan satu tangan dan condongkan badan menjauh.',
      'Tangan lain memegang dumbel di depan paha.',
      'Angkat ke samping sampai setinggi bahu, turunkan perlahan.',
    ],
    mistakes: ['Mengayun badan', 'Mengangkat melewati bahu', 'Bahu naik ke telinga'],
    youtubeQuery: 'lean away lateral raise form',
  },
  {
    id: 'barbell-upright-row',
    name: 'Barbell Upright Row (pegangan lebar)',
    slot: 'A4',
    block: 'main',
    kind: 'weighted',
    loadMode: 'barbell',
    sets: 2,
    repMin: 10,
    repMax: 15,
    restSec: 75,
    calibrationLoad: 10.85,
    siblings: [{ id: 'lateral-raise', ratio: 2.5 }],
    load: { bahu: 'berat', 'pergelangan-tangan': 'sedang' },
    muscles: 'Bahu samping, trapezius',
    cues: [
      'Berdiri, pegang barbel lebih lebar dari bahu di depan paha.',
      'Tarik barbel ke atas dengan memimpin siku, sampai sekitar dada bawah.',
      'Turunkan perlahan.',
    ],
    mistakes: ['Pegangan terlalu sempit', 'Menarik sampai dagu', 'Mengayun badan'],
    youtubeQuery: 'wide grip barbell upright row form',
  },
  {
    id: 'alternating-db-curl',
    name: 'Alternating DB Curl',
    slot: 'A5',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellPair',
    sets: 3,
    repMin: 8,
    repMax: 12,
    restSec: 75,
    calibrationLoad: 5.4,
    siblings: [
      { id: 'barbell-curl', ratio: 0.45 },
      { id: 'hammer-curl', ratio: 0.9 },
    ],
    load: { siku: 'ringan', 'pergelangan-tangan': 'ringan' },
    muscles: 'Bicep',
    cues: [
      'Berdiri, dumbel di samping paha, telapak menghadap depan.',
      'Tekuk satu siku sampai dumbel di depan bahu, turunkan perlahan.',
      'Ganti tangan bergantian; siku tetap di samping badan.',
    ],
    mistakes: ['Mengayun badan', 'Siku maju ke depan', 'Turun terlalu cepat'],
    youtubeQuery: 'alternating dumbbell curl form',
  },
  {
    id: 'concentration-curl',
    name: 'Concentration Curl (duduk)',
    slot: 'A6',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellSingle',
    sets: 2,
    repMin: 10,
    repMax: 15,
    perSide: true,
    restSec: 60,
    calibrationLoad: 4.4,
    siblings: [{ id: 'hammer-curl', ratio: 0.8 }],
    load: { siku: 'ringan' },
    muscles: 'Bicep',
    cues: [
      'Duduk di kursi, kaki terbuka, siku bertumpu di sisi dalam paha.',
      'Tekuk siku sampai dumbel mendekati bahu, remas bicep sebentar.',
      'Turunkan sampai lengan hampir lurus.',
    ],
    mistakes: ['Badan ikut mengangkat', 'Siku lepas dari paha', 'Gerakan setengah'],
    youtubeQuery: 'seated concentration curl form',
  },
  {
    id: 'zottman-curl',
    name: 'Zottman Curl',
    slot: 'A6',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellPair',
    sets: 2,
    repMin: 10,
    repMax: 15,
    restSec: 60,
    calibrationLoad: 4.4,
    siblings: [{ id: 'hammer-curl', ratio: 0.75 }],
    load: { siku: 'sedang', 'pergelangan-tangan': 'sedang' },
    muscles: 'Bicep, brachialis, lengan bawah',
    cues: [
      'Curl naik dengan telapak menghadap atas.',
      'Di atas, putar telapak menghadap bawah.',
      'Turunkan perlahan (3 detik) dengan telapak menghadap bawah, putar lagi di bawah.',
    ],
    mistakes: ['Turun terlalu cepat', 'Mengayun', 'Beban terlalu berat untuk fase turun'],
    youtubeQuery: 'zottman curl form',
  },
  // ───────────── Hari B ─────────────
  {
    id: 'underhand-row',
    name: 'Underhand Barbell Row',
    slot: 'B1',
    block: 'main',
    kind: 'weighted',
    loadMode: 'barbell',
    sets: 3,
    repMin: 8,
    repMax: 12,
    restSec: 120,
    calibrationLoad: 16.85,
    siblings: [{ id: 'bent-over-row', ratio: 1 }],
    load: { 'punggung-bawah': 'sedang', siku: 'sedang', 'pergelangan-tangan': 'ringan' },
    muscles: 'Lat, punggung atas, bicep',
    cues: [
      'Pegang barbel selebar bahu dengan telapak menghadap depan (underhand).',
      'Dorong pinggul ke belakang sampai badan ±45°, punggung lurus.',
      'Tarik barbel ke perut bawah, siku dekat badan.',
      'Turunkan terkontrol.',
    ],
    mistakes: ['Punggung membungkuk', 'Badan mengayun', 'Menarik dengan bicep saja'],
    youtubeQuery: 'underhand barbell row form',
  },
  {
    id: 'db-bent-over-row',
    name: 'DB Bent-over Row (2 dumbel)',
    slot: 'B1',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellPair',
    sets: 3,
    repMin: 8,
    repMax: 12,
    restSec: 120,
    calibrationLoad: 7.9,
    siblings: [
      { id: 'bent-over-row', ratio: 0.45 },
      { id: 'one-arm-row', ratio: 0.8 },
    ],
    load: { 'punggung-bawah': 'sedang', siku: 'ringan' },
    muscles: 'Punggung atas, lat, bicep',
    cues: [
      'Pegang dua dumbel, lutut sedikit ditekuk, badan condong ±45°.',
      'Dumbel menggantung di bawah bahu, telapak saling berhadapan.',
      'Tarik kedua siku ke arah pinggul, rapatkan tulang belikat.',
      'Turunkan terkontrol.',
    ],
    mistakes: ['Punggung membulat', 'Badan naik-turun', 'Leher mendongak'],
    youtubeQuery: 'dumbbell bent over row form',
  },
  {
    id: 'floor-pullover',
    name: 'Floor DB Pullover',
    slot: 'B2',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellSingle',
    sets: 3,
    repMin: 10,
    repMax: 15,
    restSec: 90,
    calibrationLoad: 6.4,
    siblings: [{ id: 'one-arm-row', ratio: 0.6 }],
    load: { bahu: 'sedang', siku: 'ringan' },
    muscles: 'Lat, dada, core',
    cues: [
      'Berbaring di lantai, lutut ditekuk, pegang satu dumbel dengan dua tangan di atas dada.',
      'Turunkan dumbel melewati kepala dengan siku sedikit ditekuk sampai hampir menyentuh lantai.',
      'Tarik kembali ke atas dada dengan menegangkan lat.',
    ],
    mistakes: ['Punggung bawah melengkung', 'Siku ditekuk-luruskan', 'Turun terlalu cepat'],
    youtubeQuery: 'floor dumbbell pullover form',
  },
  {
    id: 'barbell-high-row',
    name: 'Barbell High Row (pegangan lebar ke dada)',
    slot: 'B3',
    block: 'main',
    kind: 'weighted',
    loadMode: 'barbell',
    sets: 2,
    repMin: 10,
    repMax: 15,
    restSec: 75,
    calibrationLoad: 10.85,
    siblings: [{ id: 'bent-over-row', ratio: 0.6 }],
    load: { 'punggung-bawah': 'sedang', bahu: 'sedang' },
    muscles: 'Bahu belakang, punggung atas',
    cues: [
      'Pegang barbel lebar, badan condong ±45°, punggung lurus.',
      'Tarik barbel ke dada bawah dengan siku melebar ke samping.',
      'Rapatkan tulang belikat, turunkan perlahan.',
    ],
    mistakes: ['Siku menempel badan (jadi row biasa)', 'Mengayun', 'Bahu naik ke telinga'],
    youtubeQuery: 'wide grip barbell high row rear delt',
  },
  {
    id: 'prone-yt-raise',
    name: 'Prone Y-T Raise (tengkurap)',
    slot: 'B3',
    block: 'main',
    kind: 'reps',
    sets: 2,
    repMin: 6,
    repMax: 12,
    restSec: 45,
    variants: ['Prone Y-T Raise tanpa beban', 'Prone Y-T Raise memegang pelat 1,25 kg'],
    load: { bahu: 'ringan', leher: 'ringan' },
    muscles: 'Bahu belakang, punggung atas (trapezius bawah)',
    cues: [
      'Tengkurap di matras, dahi bertumpu ringan, ibu jari menghadap atas.',
      'Angkat lengan membentuk huruf Y, tahan 1 detik, turunkan.',
      'Lalu angkat lengan lurus ke samping membentuk huruf T. Y + T = 1 repetisi.',
    ],
    mistakes: ['Kepala mendongak', 'Punggung bawah melengkung', 'Mengayun'],
    youtubeQuery: 'prone y t raise form',
  },
  {
    id: 'close-grip-floor-press',
    name: 'Close-grip Barbell Floor Press',
    slot: 'B4',
    block: 'main',
    kind: 'weighted',
    loadMode: 'barbell',
    sets: 3,
    repMin: 8,
    repMax: 12,
    restSec: 90,
    calibrationLoad: 13.85,
    siblings: [
      { id: 'barbell-floor-press', ratio: 0.85 },
      { id: 'floor-press', ratio: 1.5 },
    ],
    load: { siku: 'sedang', 'pergelangan-tangan': 'sedang' },
    muscles: 'Tricep, dada',
    cues: [
      'Berbaring di lantai, pegang barbel selebar bahu.',
      'Siku dekat badan saat menurunkan sampai lengan atas menyentuh lantai.',
      'Dorong naik sampai lengan lurus.',
    ],
    mistakes: ['Pegangan terlalu sempit (pergelangan sakit)', 'Siku melebar', 'Lengan dibanting'],
    youtubeQuery: 'close grip barbell floor press form',
  },
  {
    id: 'db-kickback',
    name: 'DB Kickback',
    slot: 'B5',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellPair',
    sets: 2,
    repMin: 12,
    repMax: 15,
    restSec: 60,
    calibrationLoad: 2.9,
    siblings: [
      { id: 'overhead-tricep-ext', ratio: 0.4 },
      { id: 'lying-tricep-ext', ratio: 0.7 },
    ],
    load: { siku: 'ringan', 'punggung-bawah': 'ringan' },
    muscles: 'Tricep',
    cues: [
      'Badan condong ±45°, punggung lurus, lengan atas sejajar badan.',
      'Luruskan siku ke belakang sampai lengan lurus, tahan 1 detik.',
      'Tekuk kembali tanpa menggerakkan lengan atas.',
    ],
    mistakes: ['Lengan atas ikut berayun', 'Beban terlalu berat', 'Punggung membulat'],
    youtubeQuery: 'dumbbell tricep kickback form',
  },
  // ───────────── Hari C ─────────────
  {
    id: 'suitcase-box-squat',
    name: 'Suitcase Box Squat ke Kursi',
    slot: 'C1',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellPair',
    sets: 3,
    repMin: 8,
    repMax: 12,
    restSec: 120,
    lowerBody: true,
    calibrationLoad: 7.9,
    siblings: [{ id: 'goblet-box-squat', ratio: 0.55 }],
    kneeNote: 'Lutut sedang nyeri: pakai kursi lebih tinggi (tambah bantal) agar jongkok lebih dangkal.',
    load: { lutut: 'ringan', pinggul: 'ringan' },
    muscles: 'Paha depan, bokong',
    cues: [
      'Pegang dua dumbel di samping badan, kursi di belakang.',
      'Dorong pinggul ke belakang, turun sampai bokong menyentuh kursi.',
      'Dada tetap tegak, dorong lantai dengan seluruh telapak untuk berdiri.',
    ],
    mistakes: ['Lutut masuk ke dalam', 'Badan membungkuk', 'Menjatuhkan diri ke kursi'],
    youtubeQuery: 'dumbbell suitcase box squat form',
  },
  {
    id: 'goblet-squat',
    name: 'Goblet Squat tanpa Kursi',
    slot: 'C1',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellSingle',
    sets: 3,
    repMin: 8,
    repMax: 12,
    restSec: 120,
    lowerBody: true,
    calibrationLoad: 9.4,
    siblings: [{ id: 'goblet-box-squat', ratio: 0.9 }],
    load: { lutut: 'sedang', pinggul: 'ringan' },
    muscles: 'Paha depan, bokong, core',
    cues: [
      'Pegang satu dumbel vertikal di depan dada, kaki selebar bahu.',
      'Turun terkontrol sedalam yang nyaman untuk lutut (paha sejajar lantai atau sedikit di atasnya).',
      'Dorong lantai dengan seluruh telapak untuk berdiri.',
    ],
    mistakes: ['Lutut masuk ke dalam', 'Tumit terangkat', 'Turun terlalu dalam saat lutut belum siap'],
    youtubeQuery: 'goblet squat form',
  },
  {
    id: 'db-rdl',
    name: 'DB Romanian Deadlift',
    slot: 'C2',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellPair',
    sets: 3,
    repMin: 8,
    repMax: 12,
    restSec: 120,
    lowerBody: true,
    calibrationLoad: 9.4,
    siblings: [{ id: 'rdl', ratio: 0.45 }],
    load: { 'punggung-bawah': 'sedang', pinggul: 'ringan' },
    muscles: 'Hamstring, bokong, punggung bawah',
    cues: [
      'Berdiri, dua dumbel di depan paha, lutut sedikit ditekuk (tetap).',
      'Dorong pinggul ke belakang, dumbel meluncur dekat kaki.',
      'Turun sampai terasa tarikan di paha belakang, punggung tetap lurus.',
      'Dorong pinggul ke depan untuk berdiri.',
    ],
    mistakes: ['Punggung membulat', 'Dumbel menjauh dari kaki', 'Jongkok seperti squat'],
    youtubeQuery: 'dumbbell romanian deadlift form',
  },
  {
    id: 'single-leg-rdl',
    name: 'Single-leg DB RDL',
    slot: 'C2',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellSingle',
    sets: 2,
    repMin: 8,
    repMax: 12,
    perSide: true,
    restSec: 90,
    lowerBody: true,
    calibrationLoad: 6.4,
    siblings: [
      { id: 'db-rdl', ratio: 0.65 },
      { id: 'rdl', ratio: 0.3 },
    ],
    load: { lutut: 'sedang', pinggul: 'sedang', engkel: 'sedang' },
    muscles: 'Hamstring, bokong, keseimbangan',
    cues: [
      'Berdiri dengan satu kaki, tangan bebas boleh berpegangan ke tembok/kursi.',
      'Pegang dumbel di tangan yang berlawanan dengan kaki tumpuan.',
      'Condongkan badan ke depan sambil kaki belakang terangkat lurus, pinggul tetap sejajar.',
      'Kembali berdiri dengan mendorong pinggul ke depan.',
    ],
    mistakes: ['Pinggul berputar terbuka', 'Punggung membulat', 'Lutut tumpuan terkunci lurus'],
    youtubeQuery: 'single leg dumbbell rdl form',
  },
  {
    id: 'single-leg-glute-bridge',
    name: 'Single-leg Glute Bridge',
    slot: 'C3',
    block: 'main',
    kind: 'reps',
    sets: 3,
    repMin: 8,
    repMax: 15,
    perSide: true,
    restSec: 60,
    lowerBody: true,
    variants: ['Single-leg Glute Bridge', 'Single-leg Glute Bridge + dumbel di pinggul'],
    load: { pinggul: 'sedang' },
    muscles: 'Bokong, hamstring',
    cues: [
      'Berbaring, satu lutut ditekuk dengan telapak menapak, kaki lain lurus terangkat.',
      'Dorong lewat tumit kaki tumpuan, angkat pinggul sampai lurus dari bahu ke lutut.',
      'Tahan 1 detik, turunkan perlahan.',
    ],
    mistakes: ['Pinggul miring', 'Punggung melengkung', 'Mendorong dengan ujung kaki'],
    youtubeQuery: 'single leg glute bridge form',
  },
  {
    id: 'split-squat',
    name: 'Split Squat Statis',
    slot: 'C4',
    block: 'main',
    kind: 'reps',
    sets: 2,
    repMin: 6,
    repMax: 12,
    perSide: true,
    restSec: 75,
    lowerBody: true,
    variants: ['Split Squat statis (pegangan kursi)', 'Split Squat statis sambil pegang 2 dumbel ringan'],
    load: { lutut: 'sedang', engkel: 'ringan', pinggul: 'ringan' },
    muscles: 'Paha depan, bokong, keseimbangan',
    cues: [
      'Berdiri dengan satu kaki di depan dan satu di belakang (langkah panjang), pegang sandaran kursi.',
      'Turunkan badan lurus ke bawah sampai lutut belakang mendekati lantai (sedalam yang nyaman).',
      'Dorong lewat kaki depan untuk naik. Kaki tidak berpindah.',
    ],
    mistakes: ['Lutut depan masuk ke dalam', 'Badan condong jauh ke depan', 'Langkah terlalu pendek'],
    youtubeQuery: 'static split squat form',
  },
  {
    id: 'reverse-lunge',
    name: 'Reverse Lunge',
    slot: 'C4',
    block: 'main',
    kind: 'reps',
    sets: 2,
    repMin: 6,
    repMax: 10,
    perSide: true,
    restSec: 90,
    lowerBody: true,
    variants: ['Reverse Lunge (pegangan kursi)', 'Reverse Lunge tanpa pegangan'],
    load: { lutut: 'berat', pinggul: 'sedang', engkel: 'ringan' },
    muscles: 'Paha depan, bokong, keseimbangan',
    cues: [
      'Berdiri tegak, boleh berpegangan ke sandaran kursi.',
      'Langkahkan satu kaki ke belakang, turunkan badan sampai lutut belakang mendekati lantai.',
      'Dorong lewat kaki depan untuk kembali berdiri, ganti sisi.',
    ],
    mistakes: ['Lutut depan melewati jauh ujung kaki', 'Badan goyah', 'Lutut belakang dibanting'],
    youtubeQuery: 'reverse lunge form',
  },
  {
    id: 'single-leg-calf-raise',
    name: 'Single-leg Calf Raise (anak tangga)',
    slot: 'C5',
    block: 'main',
    kind: 'reps',
    sets: 3,
    repMin: 10,
    repMax: 20,
    perSide: true,
    restSec: 45,
    variants: ['Single-leg Calf Raise di anak tangga', 'Single-leg Calf Raise di anak tangga + dumbel'],
    load: { engkel: 'sedang', 'tulang-kering': 'sedang' },
    muscles: 'Betis',
    cues: [
      'Berdiri dengan ujung satu kaki di tepi anak tangga, pegang tembok/pegangan tangga.',
      'Turunkan tumit di bawah anak tangga, lalu jinjit setinggi mungkin.',
      'Tahan 1 detik di atas, turunkan perlahan.',
    ],
    mistakes: ['Memantul cepat', 'Gerakan setengah', 'Lutut ditekuk-tekuk'],
    youtubeQuery: 'single leg calf raise on step form',
  },
  {
    id: 'seated-calf-raise',
    name: 'Seated Calf Raise (DB di lutut)',
    slot: 'C5',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellPair',
    sets: 3,
    repMin: 15,
    repMax: 20,
    restSec: 45,
    calibrationLoad: 7.9,
    siblings: [{ id: 'calf-raise', ratio: 1 }],
    load: { engkel: 'ringan', 'tulang-kering': 'ringan' },
    muscles: 'Betis (soleus)',
    cues: [
      'Duduk di kursi, telapak kaki menapak, dumbel diletakkan di atas lutut (alasi handuk).',
      'Angkat tumit setinggi mungkin, tahan 1 detik.',
      'Turunkan tumit perlahan.',
    ],
    mistakes: ['Memantul cepat', 'Gerakan setengah'],
    youtubeQuery: 'seated dumbbell calf raise form',
  },
  // ───────────── Core ─────────────
  {
    id: 'suitcase-carry',
    name: 'Suitcase Carry / Hold',
    slot: 'core',
    block: 'core',
    coreType: 'other',
    carry: true,
    kind: 'timed',
    sets: 2,
    repMin: 20,
    repMax: 45,
    perSide: true,
    restSec: 45,
    load: { 'punggung-bawah': 'sedang', 'pergelangan-tangan': 'ringan' },
    muscles: 'Core samping, genggaman, bahu',
    cues: [
      'Pegang satu dumbel (yang sedang terpasang) di satu sisi badan.',
      'Berdiri atau berjalan pelan tanpa miring — bahu dan pinggul tetap sejajar.',
      'Ganti sisi.',
    ],
    mistakes: ['Badan miring ke arah dumbel', 'Bahu terangkat', 'Menahan napas'],
    youtubeQuery: 'suitcase carry form',
  },
  {
    id: 'farmer-carry',
    name: 'Farmer Carry / Hold',
    slot: 'core',
    block: 'core',
    coreType: 'other',
    carry: true,
    kind: 'timed',
    sets: 2,
    repMin: 30,
    repMax: 60,
    restSec: 45,
    load: { 'pergelangan-tangan': 'sedang', 'punggung-bawah': 'ringan' },
    muscles: 'Core, genggaman, punggung atas',
    cues: [
      'Pegang dua dumbel (yang sedang terpasang) di samping badan.',
      'Berdiri tegak atau berjalan pelan, bahu turun dan ke belakang.',
      'Kencangkan perut, napas tetap jalan.',
    ],
    mistakes: ['Bahu membungkuk', 'Langkah terburu-buru', 'Menahan napas'],
    youtubeQuery: 'farmer carry form',
  },
  {
    id: 'reverse-crunch',
    name: 'Reverse Crunch',
    slot: 'core',
    block: 'core',
    coreType: 'other',
    kind: 'reps',
    sets: 2,
    repMin: 8,
    repMax: 15,
    restSec: 30,
    load: { 'punggung-bawah': 'ringan' },
    muscles: 'Perut bawah',
    cues: [
      'Berbaring, tangan di samping badan, lutut ditekuk 90° dan terangkat.',
      'Gulung pinggul ke arah dada sampai bokong sedikit terangkat dari lantai.',
      'Turunkan perlahan tanpa mengayun.',
    ],
    mistakes: ['Mengayun kaki', 'Turun terlalu cepat', 'Leher tegang'],
    youtubeQuery: 'reverse crunch form',
  },
  {
    id: 'bear-plank',
    name: 'Bear Plank Hold',
    slot: 'core',
    block: 'core',
    coreType: 'anti',
    kind: 'timed',
    sets: 2,
    repMin: 15,
    repMax: 40,
    restSec: 30,
    load: { 'pergelangan-tangan': 'sedang', bahu: 'ringan' },
    muscles: 'Core, bahu',
    cues: [
      'Posisi merangkak, tangan di bawah bahu, lutut di bawah pinggul.',
      'Angkat lutut 2–3 cm dari lantai, punggung datar.',
      'Tahan sambil bernapas pelan.',
    ],
    mistakes: ['Pinggul terlalu tinggi', 'Punggung melengkung', 'Menahan napas'],
    youtubeQuery: 'bear plank hold form',
  },
];

/** Variasi kaki tambahan (tetap memakai alat yang sama, tanpa alat baru). */
const LEG_BANK: RawExercise[] = [
  // ───────────── C1 Squat ─────────────
  {
    id: 'sumo-goblet-squat',
    name: 'Sumo Goblet Squat ke Kursi',
    slot: 'C1',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellSingle',
    sets: 3,
    repMin: 8,
    repMax: 12,
    restSec: 120,
    lowerBody: true,
    calibrationLoad: 9.4,
    siblings: [{ id: 'goblet-box-squat', ratio: 1 }],
    kneeNote: 'Lutut sedang dalam pemulihan: pakai kursi lebih tinggi agar jongkok lebih dangkal.',
    load: { lutut: 'ringan', pinggul: 'sedang' },
    muscles: 'Paha dalam, bokong, paha depan',
    cues: [
      'Kaki dibuka lebar (lebih lebar dari bahu), ujung kaki mengarah keluar ±45°, kursi di belakang.',
      'Pegang satu dumbel vertikal di depan dada.',
      'Turun sampai bokong menyentuh kursi, lutut searah ujung kaki.',
      'Dorong lantai untuk berdiri, kencangkan bokong di atas.',
    ],
    mistakes: ['Lutut masuk ke dalam', 'Tumit terangkat', 'Badan terlalu condong ke depan'],
    youtubeQuery: 'sumo goblet box squat form',
  },
  {
    id: 'heels-elevated-goblet-squat',
    name: 'Heels-elevated Goblet Squat',
    slot: 'C1',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellSingle',
    sets: 3,
    repMin: 8,
    repMax: 12,
    restSec: 120,
    lowerBody: true,
    calibrationLoad: 7.9,
    siblings: [{ id: 'goblet-box-squat', ratio: 0.85 }],
    load: { lutut: 'berat', engkel: 'ringan' },
    muscles: 'Paha depan',
    cues: [
      'Letakkan kedua tumit di atas pelat beban (±2–3 cm), kaki selebar pinggul.',
      'Pegang satu dumbel vertikal di depan dada, badan tegak.',
      'Turun dalam dan terkontrol, lutut maju melewati ujung kaki.',
      'Dorong naik lewat seluruh telapak kaki.',
    ],
    mistakes: ['Pelat bergeser', 'Badan membungkuk', 'Turun terlalu cepat'],
    youtubeQuery: 'heels elevated goblet squat form',
  },
  {
    id: 'tempo-goblet-box-squat',
    name: 'Tempo Goblet Box Squat (turun 3 detik)',
    slot: 'C1',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellSingle',
    sets: 3,
    repMin: 6,
    repMax: 10,
    restSec: 120,
    lowerBody: true,
    calibrationLoad: 7.9,
    siblings: [{ id: 'goblet-box-squat', ratio: 0.8 }],
    kneeNote: 'Lutut sedang dalam pemulihan: pakai kursi lebih tinggi agar jongkok lebih dangkal.',
    load: { lutut: 'ringan', pinggul: 'ringan' },
    muscles: 'Paha depan, bokong (kontrol)',
    cues: [
      'Sama seperti Goblet Box Squat: satu dumbel di depan dada, kursi di belakang.',
      'Hitung 3 detik saat turun sampai bokong menyentuh kursi.',
      'Jeda 1 detik tanpa duduk penuh, lalu berdiri normal.',
    ],
    mistakes: ['Turun lebih cepat dari 3 detik', 'Duduk penuh dan rileks di kursi', 'Lutut masuk ke dalam'],
    youtubeQuery: 'tempo goblet box squat',
  },
  // ───────────── C2 Hinge ─────────────
  {
    id: 'sumo-db-deadlift',
    name: 'Sumo DB Deadlift',
    slot: 'C2',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellSingle',
    sets: 3,
    repMin: 8,
    repMax: 12,
    restSec: 120,
    lowerBody: true,
    calibrationLoad: 12.4,
    siblings: [
      { id: 'db-rdl', ratio: 1.8 },
      { id: 'rdl', ratio: 0.8 },
    ],
    load: { 'punggung-bawah': 'sedang', pinggul: 'sedang' },
    muscles: 'Bokong, paha dalam, hamstring',
    cues: [
      'Kaki dibuka lebar, ujung kaki sedikit keluar, satu dumbel berdiri di antara kaki.',
      'Dorong pinggul ke belakang, tekuk lutut, pegang dumbel dengan dua tangan, punggung lurus.',
      'Berdiri dengan mendorong lantai dan mengunci pinggul di atas.',
      'Turunkan terkontrol sampai dumbel hampir menyentuh lantai.',
    ],
    mistakes: ['Punggung membulat', 'Lutut masuk ke dalam', 'Menarik dengan lengan'],
    youtubeQuery: 'sumo dumbbell deadlift form',
  },
  {
    id: 'b-stance-db-rdl',
    name: 'B-stance DB RDL',
    slot: 'C2',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellPair',
    sets: 3,
    repMin: 8,
    repMax: 12,
    perSide: true,
    restSec: 90,
    lowerBody: true,
    calibrationLoad: 7.9,
    siblings: [
      { id: 'db-rdl', ratio: 0.8 },
      { id: 'rdl', ratio: 0.35 },
    ],
    load: { 'punggung-bawah': 'sedang', pinggul: 'sedang' },
    muscles: 'Hamstring & bokong (satu sisi dominan)',
    cues: [
      'Satu kaki di depan menopang beban, kaki lain sedikit di belakang dengan ujung jari menapak sebagai penyangga.',
      'Pegang dua dumbel, lutut kaki depan sedikit ditekuk.',
      'Dorong pinggul ke belakang sampai terasa tarikan di hamstring kaki depan, punggung lurus.',
      'Berdiri dengan mendorong pinggul ke depan. Selesaikan satu sisi, lalu ganti.',
    ],
    mistakes: ['Bertumpu terlalu banyak di kaki belakang', 'Punggung membulat', 'Pinggul berputar'],
    youtubeQuery: 'b stance dumbbell rdl form',
  },
  {
    id: 'db-good-morning',
    name: 'DB Good Morning',
    slot: 'C2',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellSingle',
    sets: 3,
    repMin: 10,
    repMax: 15,
    restSec: 90,
    lowerBody: true,
    calibrationLoad: 6.4,
    siblings: [{ id: 'rdl', ratio: 0.4 }],
    load: { 'punggung-bawah': 'sedang', pinggul: 'ringan' },
    muscles: 'Hamstring, bokong, punggung bawah',
    cues: [
      'Peluk satu dumbel di dada, kaki selebar pinggul, lutut sedikit ditekuk.',
      'Dorong pinggul ke belakang dan condongkan badan sampai hampir sejajar lantai (atau sampai hamstring terasa tertarik).',
      'Punggung tetap lurus; berdiri kembali dengan mendorong pinggul ke depan.',
    ],
    mistakes: ['Punggung membulat', 'Lutut ditekuk terlalu banyak (jadi squat)', 'Terlalu berat'],
    youtubeQuery: 'dumbbell good morning form',
  },
  // ───────────── C3 Glute ─────────────
  {
    id: 'barbell-hip-thrust',
    name: 'Barbell Hip Thrust (punggung di kursi)',
    slot: 'C3',
    block: 'main',
    kind: 'weighted',
    loadMode: 'barbell',
    sets: 3,
    repMin: 8,
    repMax: 12,
    restSec: 120,
    lowerBody: true,
    calibrationLoad: 19.85,
    siblings: [{ id: 'hip-thrust', ratio: 1.1 }],
    load: { pinggul: 'sedang' },
    muscles: 'Bokong, hamstring',
    cues: [
      'Punggung atas bersandar di tepi kursi yang kokoh (dorong kursi ke tembok agar tidak bergeser).',
      'Barbel di lipatan pinggul (alasi handuk), kaki selebar pinggul, lutut ±90° di posisi atas.',
      'Dorong lewat tumit sampai badan lurus dari bahu ke lutut, dagu sedikit ditekuk.',
      'Kencangkan bokong 1 detik, turunkan terkontrol.',
    ],
    mistakes: ['Kursi bergeser', 'Punggung bawah melengkung di atas', 'Mendorong dengan ujung kaki'],
    youtubeQuery: 'barbell hip thrust bench form',
  },
  {
    id: 'db-frog-pump',
    name: 'DB Frog Pump',
    slot: 'C3',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellSingle',
    sets: 3,
    repMin: 15,
    repMax: 25,
    restSec: 60,
    lowerBody: true,
    calibrationLoad: 9.4,
    siblings: [{ id: 'hip-thrust', ratio: 0.4 }],
    load: { pinggul: 'ringan' },
    muscles: 'Bokong',
    cues: [
      'Berbaring, telapak kaki saling menempel dan lutut terbuka ke samping (seperti kaki katak).',
      'Letakkan satu dumbel di pinggul, pegang dengan dua tangan.',
      'Angkat pinggul dengan mengencangkan bokong, turunkan perlahan.',
    ],
    mistakes: ['Punggung melengkung', 'Gerakan terlalu cepat tanpa kontraksi'],
    youtubeQuery: 'dumbbell frog pump',
  },
  {
    id: 'b-stance-db-hip-thrust',
    name: 'B-stance DB Hip Thrust (punggung di kursi)',
    slot: 'C3',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellSingle',
    sets: 3,
    repMin: 8,
    repMax: 12,
    perSide: true,
    restSec: 90,
    lowerBody: true,
    calibrationLoad: 9.4,
    siblings: [{ id: 'hip-thrust', ratio: 0.5 }],
    load: { pinggul: 'sedang' },
    muscles: 'Bokong (satu sisi dominan), hamstring',
    cues: [
      'Punggung atas bersandar di tepi kursi, satu dumbel di pinggul.',
      'Satu kaki menapak penuh, kaki lain sedikit maju dengan tumit saja yang menyentuh lantai.',
      'Angkat pinggul terutama dengan kaki yang menapak penuh, tahan 1 detik.',
      'Selesaikan satu sisi, lalu ganti.',
    ],
    mistakes: ['Pinggul miring', 'Kaki penyangga ikut mendorong', 'Kursi bergeser'],
    youtubeQuery: 'b stance hip thrust dumbbell',
  },
  // ───────────── C4 Satu kaki ─────────────
  {
    id: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat (kaki belakang di kursi)',
    slot: 'C4',
    block: 'main',
    kind: 'reps',
    sets: 2,
    repMin: 6,
    repMax: 12,
    perSide: true,
    restSec: 90,
    lowerBody: true,
    variants: ['Bulgarian Split Squat (pegangan tembok)', 'Bulgarian Split Squat sambil pegang 2 dumbel ringan'],
    load: { lutut: 'berat', engkel: 'sedang', pinggul: 'sedang' },
    muscles: 'Paha depan, bokong, keseimbangan',
    cues: [
      'Berdiri membelakangi kursi, letakkan punggung kaki belakang di dudukan kursi.',
      'Kaki depan cukup jauh sehingga saat turun lutut depan kira-kira di atas pergelangan kaki.',
      'Turunkan badan lurus ke bawah sampai paha depan mendekati sejajar lantai.',
      'Dorong lewat tumit kaki depan untuk naik.',
    ],
    mistakes: ['Kaki depan terlalu dekat dengan kursi', 'Lutut depan masuk ke dalam', 'Mendorong dengan kaki belakang'],
    youtubeQuery: 'bulgarian split squat form beginner',
  },
  {
    id: 'lateral-lunge',
    name: 'Lateral Lunge',
    slot: 'C4',
    block: 'main',
    kind: 'reps',
    sets: 2,
    repMin: 6,
    repMax: 12,
    perSide: true,
    restSec: 75,
    lowerBody: true,
    variants: ['Lateral Lunge (setengah dalam)', 'Lateral Lunge penuh', 'Lateral Lunge sambil pegang dumbel di dada'],
    load: { lutut: 'sedang', pinggul: 'sedang' },
    muscles: 'Paha dalam, bokong, paha depan',
    cues: [
      'Berdiri dengan kaki rapat, lalu melangkah lebar ke samping.',
      'Tekuk lutut kaki yang melangkah dan dorong pinggul ke belakang; kaki lain tetap lurus.',
      'Lutut searah ujung kaki, telapak menapak penuh.',
      'Dorong kembali ke posisi awal, ganti sisi.',
    ],
    mistakes: ['Lutut melewati jauh ujung kaki ke dalam', 'Tumit terangkat', 'Badan membungkuk'],
    youtubeQuery: 'lateral lunge proper form',
  },
  {
    id: 'cossack-squat',
    name: 'Cossack Squat',
    slot: 'C4',
    block: 'main',
    kind: 'reps',
    sets: 2,
    repMin: 5,
    repMax: 10,
    perSide: true,
    restSec: 75,
    lowerBody: true,
    variants: ['Cossack Squat (pegangan kursi)', 'Cossack Squat tanpa pegangan'],
    load: { lutut: 'berat', engkel: 'berat', pinggul: 'sedang' },
    muscles: 'Paha dalam, paha depan, bokong, mobilitas pinggul',
    cues: [
      'Berdiri dengan kaki sangat lebar, pegang sandaran kursi di depan untuk keseimbangan.',
      'Geser berat badan ke satu sisi dan jongkok dalam di kaki itu, kaki lain lurus dengan ujung jari menghadap atas.',
      'Turun sedalam yang nyaman, tumit kaki yang ditekuk tetap menapak.',
      'Kembali ke tengah, ganti sisi.',
    ],
    mistakes: ['Tumit terangkat', 'Turun terlalu dalam di luar batas nyaman', 'Badan jatuh ke depan'],
    youtubeQuery: 'cossack squat beginner form',
  },
  {
    id: 'step-down',
    name: 'Step-down Pelan (anak tangga)',
    slot: 'C4',
    block: 'main',
    kind: 'reps',
    sets: 2,
    repMin: 6,
    repMax: 12,
    perSide: true,
    restSec: 75,
    lowerBody: true,
    variants: ['Step-down pelan (pegangan tembok)', 'Step-down pelan tanpa pegangan'],
    load: { lutut: 'sedang', engkel: 'ringan' },
    muscles: 'Paha depan (kontrol turun), bokong',
    cues: [
      'Berdiri dengan satu kaki di atas anak tangga, kaki lain menggantung di samping/depan.',
      'Tekuk lutut kaki tumpuan perlahan (3 detik) sampai tumit kaki lain menyentuh lantai ringan.',
      'Lutut tumpuan searah jari kaki, pinggul sejajar.',
      'Naik kembali dengan kaki tumpuan.',
    ],
    mistakes: ['Lutut masuk ke dalam', 'Menjatuhkan diri', 'Pinggul miring'],
    youtubeQuery: 'eccentric step down exercise knee',
  },
  // ───────────── C5 Betis & tulang kering ─────────────
  {
    id: 'tibialis-raise',
    name: 'Tibialis Raise (punggung di tembok)',
    slot: 'C5',
    block: 'main',
    kind: 'reps',
    sets: 2,
    repMin: 15,
    repMax: 25,
    restSec: 45,
    load: { 'tulang-kering': 'ringan' },
    muscles: 'Tulang kering (tibialis anterior)',
    cues: [
      'Bersandar dengan punggung di tembok, tumit ±30 cm dari tembok.',
      'Angkat ujung kaki setinggi mungkin, tumit tetap di lantai.',
      'Turunkan perlahan.',
    ],
    mistakes: ['Memantul cepat', 'Lutut ditekuk'],
    youtubeQuery: 'tibialis raise against wall',
  },
  {
    id: 'donkey-calf-raise',
    name: 'Donkey Calf Raise (tangan di kursi)',
    slot: 'C5',
    block: 'main',
    kind: 'reps',
    sets: 3,
    repMin: 12,
    repMax: 20,
    restSec: 45,
    variants: ['Donkey Calf Raise dua kaki', 'Donkey Calf Raise satu kaki'],
    load: { engkel: 'sedang', 'tulang-kering': 'ringan' },
    muscles: 'Betis (gastrocnemius)',
    cues: [
      'Bungkukkan badan ±90°, tangan bertumpu di sandaran kursi, kaki lurus.',
      'Jinjit setinggi mungkin, tahan 1 detik.',
      'Turunkan tumit perlahan.',
    ],
    mistakes: ['Lutut ditekuk', 'Memantul cepat', 'Punggung membulat'],
    youtubeQuery: 'donkey calf raise bodyweight',
  },
  // ───────────── C6 Hamstring & paha samping ─────────────
  {
    id: 'elevated-hamstring-bridge',
    name: 'Elevated Hamstring Bridge (tumit di kursi)',
    slot: 'C6',
    block: 'main',
    kind: 'reps',
    sets: 3,
    repMin: 8,
    repMax: 15,
    restSec: 60,
    lowerBody: true,
    variants: ['Elevated Hamstring Bridge dua kaki', 'Elevated Hamstring Bridge satu kaki'],
    load: { pinggul: 'ringan', lutut: 'ringan' },
    muscles: 'Hamstring, bokong',
    cues: [
      'Berbaring, letakkan kedua tumit di dudukan kursi, lutut sedikit ditekuk.',
      'Tekan tumit ke kursi dan angkat pinggul sampai lurus dari bahu ke lutut.',
      'Tahan 1 detik, turunkan perlahan.',
    ],
    mistakes: ['Kram hamstring karena terlalu cepat', 'Punggung melengkung', 'Kursi bergeser'],
    youtubeQuery: 'elevated hamstring bridge chair',
  },
  {
    id: 'prone-db-leg-curl',
    name: 'Prone DB Leg Curl',
    slot: 'C6',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellSingle',
    sets: 2,
    repMin: 10,
    repMax: 15,
    restSec: 60,
    lowerBody: true,
    calibrationLoad: 2.9,
    load: { lutut: 'sedang' },
    muscles: 'Hamstring',
    cues: [
      'Tengkurap di matras, jepit satu dumbel ringan di antara kedua telapak kaki (minta bantuan memasang atau pasang sambil duduk).',
      'Tekuk lutut, bawa dumbel ke atas sampai betis tegak.',
      'Turunkan perlahan tanpa membiarkan dumbel lepas.',
    ],
    mistakes: ['Dumbel terlalu berat dan lepas', 'Pinggul terangkat dari matras', 'Gerakan menyentak'],
    youtubeQuery: 'prone dumbbell leg curl floor',
  },
  {
    id: 'side-lying-leg-raise',
    name: 'Side-lying Leg Raise',
    slot: 'C6',
    block: 'main',
    kind: 'reps',
    sets: 2,
    repMin: 12,
    repMax: 20,
    perSide: true,
    restSec: 45,
    load: { pinggul: 'ringan' },
    muscles: 'Paha samping luar (abduktor), bokong samping',
    cues: [
      'Berbaring menyamping, kaki bawah sedikit ditekuk untuk stabil.',
      'Angkat kaki atas lurus ke atas ±45°, ujung kaki sedikit mengarah ke bawah.',
      'Turunkan perlahan, ganti sisi.',
    ],
    mistakes: ['Badan berguling ke belakang', 'Mengayun', 'Ujung kaki mengarah ke atas'],
    youtubeQuery: 'side lying leg raise form',
  },
  {
    id: 'clamshell',
    name: 'Clamshell',
    slot: 'C6',
    block: 'main',
    kind: 'reps',
    sets: 2,
    repMin: 12,
    repMax: 20,
    perSide: true,
    restSec: 45,
    load: { pinggul: 'ringan' },
    muscles: 'Bokong samping (gluteus medius)',
    cues: [
      'Berbaring menyamping, lutut ditekuk ±45°, kedua tumit menempel.',
      'Buka lutut atas seperti kerang tanpa memisahkan tumit dan tanpa memutar pinggul.',
      'Tahan 1 detik, tutup perlahan. Ganti sisi.',
    ],
    mistakes: ['Pinggul berguling ke belakang', 'Tumit terpisah', 'Terlalu cepat'],
    youtubeQuery: 'clamshell exercise form',
  },
  {
    id: 'copenhagen-plank',
    name: 'Copenhagen Plank (versi lutut, tumpuan kursi)',
    slot: 'C6',
    block: 'main',
    kind: 'timed',
    sets: 2,
    repMin: 10,
    repMax: 30,
    perSide: true,
    restSec: 45,
    load: { pinggul: 'sedang', lutut: 'ringan', bahu: 'ringan' },
    muscles: 'Paha dalam (adduktor), core samping',
    cues: [
      'Side plank bertumpu di lengan bawah, dengan bagian dalam lutut kaki atas diletakkan di dudukan kursi.',
      'Kaki bawah boleh menyentuh lantai ringan (versi mudah) atau diangkat.',
      'Angkat pinggul sampai badan lurus, tahan. Ganti sisi.',
    ],
    mistakes: ['Pinggul turun', 'Menumpu di ujung kaki (versi sulit) terlalu cepat', 'Bahu tidak di atas siku'],
    youtubeQuery: 'short lever copenhagen plank',
  },
];

export const SLOTS: SlotDef[] = [
  { id: 'A1', day: 'A', label: 'Dorong dada', role: 'primary', candidates: ['floor-press', 'barbell-floor-press', 'db-squeeze-press'] },
  { id: 'A2', day: 'A', label: 'Dada bodyweight', role: 'primary', candidates: ['push-up', 'db-floor-fly'] },
  { id: 'A3', day: 'A', label: 'Dorong atas', role: 'primary', candidates: ['seated-ohp', 'arnold-press', 'standing-barbell-press'] },
  { id: 'A4', day: 'A', label: 'Bahu samping', role: 'accessory', candidates: ['lateral-raise', 'lean-away-lateral-raise', 'barbell-upright-row'] },
  { id: 'A5', day: 'A', label: 'Bicep 1', role: 'accessory', candidates: ['barbell-curl', 'alternating-db-curl'] },
  { id: 'A6', day: 'A', label: 'Bicep 2', role: 'accessory', candidates: ['hammer-curl', 'concentration-curl', 'zottman-curl'] },
  { id: 'B1', day: 'B', label: 'Tarik barbel', role: 'primary', candidates: ['bent-over-row', 'underhand-row', 'db-bent-over-row'] },
  { id: 'B2', day: 'B', label: 'Tarik satu tangan / lat', role: 'primary', candidates: ['one-arm-row', 'floor-pullover'] },
  { id: 'B3', day: 'B', label: 'Bahu belakang', role: 'accessory', candidates: ['rear-delt-fly', 'barbell-high-row', 'prone-yt-raise'] },
  { id: 'B4', day: 'B', label: 'Tricep 1', role: 'accessory', candidates: ['lying-tricep-ext', 'close-grip-floor-press'] },
  { id: 'B5', day: 'B', label: 'Tricep 2', role: 'accessory', candidates: ['overhead-tricep-ext', 'db-kickback'] },
  { id: 'B6', day: 'B', label: 'Opsional', role: 'optional', candidates: ['close-grip-push-up'] },
  { id: 'C1', day: 'C', label: 'Squat', role: 'primary', candidates: ['goblet-box-squat', 'suitcase-box-squat', 'goblet-squat', 'sumo-goblet-squat', 'heels-elevated-goblet-squat', 'tempo-goblet-box-squat'] },
  { id: 'C2', day: 'C', label: 'Hinge', role: 'primary', candidates: ['rdl', 'db-rdl', 'single-leg-rdl', 'sumo-db-deadlift', 'b-stance-db-rdl', 'db-good-morning'] },
  { id: 'C3', day: 'C', label: 'Glute', role: 'primary', candidates: ['hip-thrust', 'single-leg-glute-bridge', 'barbell-hip-thrust', 'db-frog-pump', 'b-stance-db-hip-thrust'] },
  { id: 'C4', day: 'C', label: 'Satu kaki', role: 'accessory', candidates: ['step-up', 'split-squat', 'reverse-lunge', 'bulgarian-split-squat', 'lateral-lunge', 'cossack-squat', 'step-down'] },
  { id: 'C5', day: 'C', label: 'Betis & tulang kering', role: 'accessory', candidates: ['calf-raise', 'single-leg-calf-raise', 'seated-calf-raise', 'tibialis-raise', 'donkey-calf-raise'] },
  {
    id: 'C6',
    day: 'C',
    label: 'Hamstring & paha samping',
    role: 'accessory',
    candidates: ['elevated-hamstring-bridge', 'prone-db-leg-curl', 'side-lying-leg-raise', 'clamshell', 'copenhagen-plank'],
  },
];

export const SLOT_BY_ID: Record<string, SlotDef> = Object.fromEntries(SLOTS.map((s) => [s.id, s]));

export const EXERCISES: ExerciseDef[] = [...ORIGINAL, ...BANK, ...LEG_BANK].map((e) => {
  const role = SLOT_BY_ID[e.slot]?.role;
  return { ...e, primary: role === 'primary' || undefined, optional: role === 'optional' || undefined };
});

export const EXERCISE_BY_ID: Record<string, ExerciseDef> = Object.fromEntries(EXERCISES.map((e) => [e.id, e]));

/** gerakan asli (⭐) */
export const DEFAULT_IDS = new Set(ORIGINAL.map((e) => e.id));

export const CORE_POOL: ExerciseDef[] = EXERCISES.filter((e) => e.block === 'core');

export function slotsForDay(day: DayType): SlotDef[] {
  return SLOTS.filter((s) => s.day === day);
}

export function dayOf(def: ExerciseDef): TrainingDay | undefined {
  return SLOT_BY_ID[def.slot]?.day;
}

/** Semua kandidat gerakan satu hari (tanpa core). */
export function exercisesForDay(day: DayType): ExerciseDef[] {
  return EXERCISES.filter((e) => dayOf(e) === day);
}


export const DAY_LABEL: Record<DayType, string> = {
  A: 'Hari A — Dada + Bicep',
  B: 'Hari B — Back + Tricep',
  C: 'Hari C — Lower',
  AKTIF: 'Hari Aktif — Jalan & Mobilitas',
};

export const WARMUP_STEPS: { name: string; seconds: number }[] = [
  { name: 'Jalan di tempat / marching', seconds: 60 },
  { name: 'Putar bahu & lengan (depan-belakang)', seconds: 45 },
  { name: 'Putar pinggul', seconds: 30 },
  { name: 'Hip hinge tanpa beban (good morning)', seconds: 45 },
  { name: 'Ayun kaki depan-belakang (pegangan dinding)', seconds: 45 },
  { name: 'Cat-cow (merangkak)', seconds: 45 },
  { name: 'Squat ke kursi tanpa beban, pelan', seconds: 30 },
];

export const MOBILITY_STEPS: string[] = [
  'Jalan kaki santai 30–45 menit (boleh dicicil)',
  'Peregangan paha depan & belakang (30 detik/sisi)',
  'Peregangan dada di kusen pintu (30 detik)',
  'Cat-cow 10×',
  'Hip flexor stretch / lunge rendah ditopang (30 detik/sisi, lutut beralas)',
];

export function youtubeUrl(def: ExerciseDef): string {
  return `https://www.youtube.com/results?search_query=${encodeURIComponent(def.youtubeQuery)}`;
}
