/**
 * Program latihan yang disepakati:
 * A = Dada + Bicep (+ bahu depan/samping), B = Back + Tricep (+ bahu belakang),
 * C = Lower (ramah lutut). Core 5–8 menit di akhir tiap sesi.
 */
import type { DayType, ExerciseDef } from './types';

export const EXERCISES: ExerciseDef[] = [
  // ───────────── Hari A ─────────────
  {
    id: 'floor-press',
    name: 'DB Floor Press',
    day: 'A',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellPair',
    sets: 3,
    repMin: 8,
    repMax: 12,
    restSec: 120,
    primary: true,
    calibrationLoad: 6.4,
    muscles: 'Dada, tricep, bahu depan',
    cues: [
      'Berbaring di lantai, lutut ditekuk, telapak kaki menapak.',
      'Dumbel di atas dada, telapak tangan menghadap kaki.',
      'Turunkan perlahan sampai lengan atas menyentuh lantai (siku ±45° dari badan).',
      'Dorong naik sambil membuang napas, jangan sampai dumbel beradu.',
    ],
    mistakes: ['Siku melebar 90° (bahu tertekan)', 'Lengan dibanting ke lantai', 'Pinggul terangkat'],
    youtubeQuery: 'dumbbell floor press form',
  },
  {
    id: 'push-up',
    name: 'Push-up',
    day: 'A',
    block: 'main',
    kind: 'reps',
    sets: 2,
    repMin: 6,
    repMax: 15,
    restSec: 90,
    primary: true,
    variants: ['Incline Push-up (tangan di kursi)', 'Push-up di lantai'],
    muscles: 'Dada, tricep, core',
    cues: [
      'Tangan sedikit lebih lebar dari bahu.',
      'Badan lurus dari kepala sampai tumit (kencangkan perut & bokong).',
      'Turunkan dada sampai hampir menyentuh kursi/lantai, lalu dorong naik.',
    ],
    mistakes: ['Pinggul turun/melengkung', 'Kepala maju duluan', 'Gerakan setengah'],
    youtubeQuery: 'incline push up proper form',
  },
  {
    id: 'seated-ohp',
    name: 'Seated DB Overhead Press',
    day: 'A',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellPair',
    sets: 3,
    repMin: 8,
    repMax: 12,
    restSec: 120,
    primary: true,
    calibrationLoad: 5.4,
    muscles: 'Bahu depan & samping, tricep',
    cues: [
      'Duduk tegak di kursi, punggung menempel sandaran kalau ada.',
      'Dumbel di samping telinga, siku sedikit di depan badan.',
      'Dorong lurus ke atas sampai lengan hampir lurus, turunkan terkontrol.',
    ],
    mistakes: ['Punggung bawah melengkung berlebihan', 'Leher menjulur ke depan', 'Siku mengunci keras'],
    youtubeQuery: 'seated dumbbell shoulder press form',
  },
  {
    id: 'lateral-raise',
    name: 'DB Lateral Raise',
    day: 'A',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellPair',
    sets: 2,
    repMin: 12,
    repMax: 20,
    restSec: 60,
    calibrationLoad: 2.9,
    muscles: 'Bahu samping',
    cues: [
      'Berdiri, dumbel di samping paha, siku sedikit ditekuk.',
      'Angkat ke samping sampai setinggi bahu — pimpin dengan siku.',
      'Turunkan perlahan (2 detik).',
    ],
    mistakes: ['Mengayun dengan badan', 'Mengangkat melewati bahu', 'Bahu naik ke telinga'],
    youtubeQuery: 'dumbbell lateral raise form',
  },
  {
    id: 'barbell-curl',
    name: 'Barbell Curl',
    day: 'A',
    block: 'main',
    kind: 'weighted',
    loadMode: 'barbell',
    sets: 3,
    repMin: 8,
    repMax: 12,
    restSec: 75,
    calibrationLoad: 10.85,
    muscles: 'Bicep',
    cues: [
      'Berdiri, pegang barbel selebar bahu, telapak menghadap depan.',
      'Siku menempel di samping badan.',
      'Tekuk siku sampai barbel di depan bahu, turunkan perlahan.',
    ],
    mistakes: ['Mengayun pinggul', 'Siku maju ke depan', 'Turun terlalu cepat'],
    youtubeQuery: 'barbell curl proper form',
  },
  {
    id: 'hammer-curl',
    name: 'DB Hammer Curl',
    day: 'A',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellPair',
    sets: 2,
    repMin: 10,
    repMax: 15,
    restSec: 60,
    calibrationLoad: 5.4,
    muscles: 'Bicep, brachialis, lengan bawah',
    cues: ['Pegang dumbel dengan telapak saling berhadapan (seperti memegang palu).', 'Tekuk siku tanpa memutar pergelangan.', 'Turunkan perlahan.'],
    mistakes: ['Mengayun', 'Siku bergeser maju'],
    youtubeQuery: 'dumbbell hammer curl form',
  },
  // ───────────── Hari B ─────────────
  {
    id: 'bent-over-row',
    name: 'Barbell Bent-over Row',
    day: 'B',
    block: 'main',
    kind: 'weighted',
    loadMode: 'barbell',
    sets: 3,
    repMin: 8,
    repMax: 12,
    restSec: 120,
    primary: true,
    calibrationLoad: 16.85,
    muscles: 'Punggung atas, lat, bicep',
    cues: [
      'Lutut sedikit ditekuk, dorong pinggul ke belakang sampai badan ±45°.',
      'Punggung lurus (netral), barbel menggantung di bawah bahu.',
      'Tarik barbel ke perut bawah, rapatkan tulang belikat.',
      'Turunkan terkontrol tanpa mengubah posisi badan.',
    ],
    mistakes: ['Punggung membungkuk', 'Badan naik-turun mengayun', 'Menarik ke dada'],
    youtubeQuery: 'barbell bent over row form',
  },
  {
    id: 'one-arm-row',
    name: 'One-arm DB Row',
    day: 'B',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellSingle',
    sets: 3,
    repMin: 10,
    repMax: 15,
    perSide: true,
    restSec: 90,
    primary: true,
    calibrationLoad: 9.4,
    muscles: 'Lat, punggung tengah',
    cues: [
      'Satu tangan bertumpu di kursi, kaki selebar bahu, punggung datar.',
      'Dumbel menggantung lurus di bawah bahu.',
      'Tarik siku ke arah pinggul, tahan sebentar, turunkan penuh.',
    ],
    mistakes: ['Badan berputar', 'Menarik dengan bicep saja', 'Punggung membulat'],
    youtubeQuery: 'one arm dumbbell row form',
  },
  {
    id: 'rear-delt-fly',
    name: 'DB Rear Delt Fly',
    day: 'B',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellPair',
    sets: 2,
    repMin: 12,
    repMax: 20,
    restSec: 60,
    calibrationLoad: 2.9,
    muscles: 'Bahu belakang, punggung atas',
    cues: [
      'Badan membungkuk ±45–60°, punggung lurus, siku sedikit ditekuk.',
      'Buka lengan ke samping seperti sayap sampai sejajar badan.',
      'Turunkan perlahan.',
    ],
    mistakes: ['Memakai beban terlalu berat', 'Menarik dengan punggung (rowing)', 'Leher tegang'],
    youtubeQuery: 'bent over dumbbell rear delt fly form',
  },
  {
    id: 'lying-tricep-ext',
    name: 'DB Lying Triceps Extension',
    day: 'B',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellPair',
    sets: 3,
    repMin: 10,
    repMax: 15,
    restSec: 75,
    calibrationLoad: 4.4,
    muscles: 'Tricep',
    cues: [
      'Berbaring di lantai, lengan lurus ke atas, telapak saling berhadapan.',
      'Tekuk siku saja — dumbel turun ke samping kepala.',
      'Luruskan kembali tanpa menggerakkan lengan atas.',
    ],
    mistakes: ['Siku melebar', 'Lengan atas ikut bergerak', 'Turun terlalu cepat dekat kepala'],
    youtubeQuery: 'dumbbell skull crusher floor form',
  },
  {
    id: 'overhead-tricep-ext',
    name: 'DB Overhead Triceps Extension',
    day: 'B',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellSingle',
    sets: 2,
    repMin: 10,
    repMax: 15,
    restSec: 60,
    calibrationLoad: 6.4,
    muscles: 'Tricep (kepala panjang)',
    cues: [
      'Duduk tegak, pegang satu dumbel dengan dua tangan di atas kepala.',
      'Turunkan dumbel ke belakang kepala dengan menekuk siku.',
      'Luruskan kembali, siku tetap menunjuk ke depan/atas.',
    ],
    mistakes: ['Punggung melengkung', 'Siku terbuka lebar'],
    youtubeQuery: 'seated dumbbell overhead triceps extension form',
  },
  {
    id: 'close-grip-push-up',
    name: 'Close-grip Push-up',
    day: 'B',
    block: 'main',
    kind: 'reps',
    sets: 2,
    repMin: 5,
    repMax: 15,
    restSec: 60,
    optional: true,
    variants: ['Close-grip Incline Push-up (tangan di kursi)', 'Close-grip Push-up di lantai'],
    muscles: 'Tricep, dada',
    cues: ['Tangan selebar bahu atau sedikit lebih sempit.', 'Siku menempel ke badan saat turun.', 'Badan tetap lurus.'],
    mistakes: ['Siku melebar', 'Pinggul turun'],
    youtubeQuery: 'close grip incline push up form',
  },
  // ───────────── Hari C ─────────────
  {
    id: 'goblet-box-squat',
    name: 'Goblet Box Squat ke Kursi',
    day: 'C',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellSingle',
    sets: 3,
    repMin: 8,
    repMax: 12,
    restSec: 120,
    primary: true,
    lowerBody: true,
    calibrationLoad: 9.4,
    kneeNote: 'Lutut sedang nyeri: pakai kursi lebih tinggi (tambah bantal) agar jongkok lebih dangkal.',
    muscles: 'Paha depan, bokong',
    cues: [
      'Pegang satu dumbel vertikal di depan dada.',
      'Kaki selebar bahu, ujung kaki sedikit keluar, kursi di belakang.',
      'Dorong pinggul ke belakang, turun sampai bokong menyentuh kursi (jangan duduk penuh).',
      'Dorong lantai dengan seluruh telapak untuk berdiri.',
    ],
    mistakes: ['Lutut masuk ke dalam', 'Tumit terangkat', 'Menjatuhkan diri ke kursi'],
    youtubeQuery: 'goblet box squat form',
  },
  {
    id: 'rdl',
    name: 'Barbell Romanian Deadlift',
    day: 'C',
    block: 'main',
    kind: 'weighted',
    loadMode: 'barbell',
    sets: 3,
    repMin: 8,
    repMax: 12,
    restSec: 120,
    primary: true,
    lowerBody: true,
    calibrationLoad: 19.85,
    muscles: 'Hamstring, bokong, punggung bawah',
    cues: [
      'Berdiri, barbel di depan paha, lutut sedikit ditekuk (tetap).',
      'Dorong pinggul ke belakang, barbel meluncur dekat paha & tulang kering.',
      'Turun sampai terasa tarikan di paha belakang (±bawah lutut), punggung tetap lurus.',
      'Dorong pinggul ke depan untuk berdiri.',
    ],
    mistakes: ['Punggung membulat', 'Barbel menjauh dari kaki', 'Jongkok seperti squat'],
    youtubeQuery: 'barbell romanian deadlift form',
  },
  {
    id: 'hip-thrust',
    name: 'Barbell Glute Bridge / Hip Thrust (lantai)',
    day: 'C',
    block: 'main',
    kind: 'weighted',
    loadMode: 'barbell',
    sets: 3,
    repMin: 10,
    repMax: 15,
    restSec: 90,
    primary: true,
    lowerBody: true,
    calibrationLoad: 19.85,
    muscles: 'Bokong, hamstring',
    cues: [
      'Berbaring, lutut ditekuk, barbel di lipatan pinggul (alasi handuk).',
      'Dorong lewat tumit, angkat pinggul sampai badan lurus dari bahu ke lutut.',
      'Kencangkan bokong 1 detik di atas, turunkan perlahan.',
    ],
    mistakes: ['Punggung bawah melengkung di atas', 'Mendorong dengan ujung kaki'],
    youtubeQuery: 'barbell glute bridge floor form',
  },
  {
    id: 'step-up',
    name: 'Step-up Rendah',
    day: 'C',
    block: 'main',
    kind: 'reps',
    sets: 2,
    repMin: 8,
    repMax: 12,
    perSide: true,
    restSec: 75,
    lowerBody: true,
    kneeGated: true,
    variants: ['Step-up anak tangga (tanpa beban)', 'Step-up anak tangga sambil pegang dumbel ringan'],
    muscles: 'Paha depan, bokong, keseimbangan',
    cues: [
      'Seluruh telapak kaki depan di atas anak tangga.',
      'Naik dengan mendorong kaki depan, kaki belakang hanya mengikuti.',
      'Turun perlahan, lutut searah jari kaki.',
    ],
    mistakes: ['Melompat dengan kaki belakang', 'Lutut masuk ke dalam'],
    youtubeQuery: 'low step up exercise form knee friendly',
  },
  {
    id: 'calf-raise',
    name: 'Standing Calf Raise (DB)',
    day: 'C',
    block: 'main',
    kind: 'weighted',
    loadMode: 'dumbbellPair',
    sets: 3,
    repMin: 12,
    repMax: 20,
    restSec: 60,
    calibrationLoad: 7.9,
    muscles: 'Betis',
    cues: ['Pegang dumbel di samping badan (boleh satu tangan berpegangan ke dinding).', 'Jinjit setinggi mungkin, tahan 1 detik.', 'Turunkan tumit perlahan.'],
    mistakes: ['Memantul cepat', 'Lutut ditekuk-tekuk'],
    youtubeQuery: 'dumbbell standing calf raise form',
  },
  // ───────────── Core ─────────────
  {
    id: 'plank',
    name: 'Plank',
    day: 'A',
    block: 'core',
    kind: 'timed',
    sets: 2,
    repMin: 20,
    repMax: 60,
    restSec: 45,
    muscles: 'Core',
    cues: ['Bertumpu pada lengan bawah dan ujung kaki.', 'Badan lurus, kencangkan perut & bokong.', 'Napas tetap jalan.'],
    mistakes: ['Pinggul turun', 'Pinggul terlalu tinggi'],
    youtubeQuery: 'plank proper form',
  },
  {
    id: 'dead-bug',
    name: 'Dead Bug',
    day: 'A',
    block: 'core',
    kind: 'reps',
    sets: 2,
    repMin: 6,
    repMax: 12,
    perSide: true,
    restSec: 45,
    muscles: 'Core (anti-ekstensi)',
    cues: ['Berbaring, tangan lurus ke atas, lutut 90°.', 'Turunkan tangan kanan & kaki kiri bersamaan, punggung bawah tetap menempel lantai.', 'Kembali, ganti sisi.'],
    mistakes: ['Punggung bawah terangkat', 'Terlalu cepat'],
    youtubeQuery: 'dead bug exercise form',
  },
  {
    id: 'side-plank',
    name: 'Side Plank',
    day: 'B',
    block: 'core',
    kind: 'timed',
    sets: 2,
    repMin: 15,
    repMax: 45,
    perSide: true,
    restSec: 30,
    muscles: 'Core samping (oblique)',
    cues: ['Bertumpu pada satu lengan bawah, siku di bawah bahu.', 'Badan lurus menyamping; versi mudah: lutut ditekuk.', 'Angkat pinggul.'],
    mistakes: ['Pinggul turun', 'Badan condong ke depan'],
    youtubeQuery: 'side plank form beginner',
  },
  {
    id: 'bird-dog',
    name: 'Bird Dog',
    day: 'B',
    block: 'core',
    kind: 'reps',
    sets: 2,
    repMin: 6,
    repMax: 10,
    perSide: true,
    restSec: 30,
    muscles: 'Core, punggung bawah, bokong',
    cues: ['Posisi merangkak, tangan di bawah bahu, lutut di bawah pinggul.', 'Luruskan tangan kanan & kaki kiri, tahan 2 detik.', 'Kembali, ganti sisi.'],
    mistakes: ['Pinggul berputar', 'Punggung melengkung'],
    youtubeQuery: 'bird dog exercise form',
  },
  {
    id: 'glute-bridge-hold',
    name: 'Glute Bridge Hold',
    day: 'C',
    block: 'core',
    kind: 'timed',
    sets: 2,
    repMin: 20,
    repMax: 60,
    restSec: 30,
    muscles: 'Bokong, core',
    cues: ['Berbaring, lutut ditekuk.', 'Angkat pinggul sampai lurus dari bahu ke lutut, tahan.', 'Kencangkan bokong, jangan melengkungkan punggung.'],
    mistakes: ['Punggung melengkung', 'Pinggul turun perlahan'],
    youtubeQuery: 'glute bridge hold form',
  },
  {
    id: 'hollow-hold',
    name: 'Hollow Hold (versi mudah)',
    day: 'C',
    block: 'core',
    kind: 'timed',
    sets: 2,
    repMin: 10,
    repMax: 30,
    restSec: 30,
    muscles: 'Core depan',
    cues: ['Berbaring, punggung bawah ditekan ke lantai.', 'Angkat bahu & kaki sedikit, lutut boleh ditekuk (versi mudah).', 'Tahan tanpa punggung bawah terangkat.'],
    mistakes: ['Punggung bawah terangkat dari lantai', 'Menahan napas'],
    youtubeQuery: 'hollow hold beginner tuck',
  },
];

export const EXERCISE_BY_ID: Record<string, ExerciseDef> = Object.fromEntries(EXERCISES.map((e) => [e.id, e]));

export function exercisesForDay(day: DayType): ExerciseDef[] {
  return EXERCISES.filter((e) => e.day === day);
}

export const DAY_LABEL: Record<DayType, string> = {
  A: 'Hari A — Dada + Bicep',
  B: 'Hari B — Back + Tricep',
  C: 'Hari C — Lower',
  AKTIF: 'Hari Aktif — Jalan & Mobilitas',
};

export const WARMUP_STEPS: { name: string; seconds: number }[] = [
  { name: 'Jalan di tempat / marching', seconds: 60 },
  { name: 'Putar bahu & lengan (depan-belakang)', seconds: 45 },
  { name: 'Putar pinggul', seconds: 30 },
  { name: 'Hip hinge tanpa beban (good morning)', seconds: 45 },
  { name: 'Ayun kaki depan-belakang (pegangan dinding)', seconds: 45 },
  { name: 'Cat-cow (merangkak)', seconds: 45 },
  { name: 'Squat ke kursi tanpa beban, pelan', seconds: 30 },
];

export const MOBILITY_STEPS: string[] = [
  'Jalan kaki santai 30–45 menit (boleh dicicil)',
  'Peregangan paha depan & belakang (30 detik/sisi)',
  'Peregangan dada di kusen pintu (30 detik)',
  'Cat-cow 10×',
  'Hip flexor stretch / lunge rendah ditopang (30 detik/sisi, lutut beralas)',
];

export function youtubeUrl(def: ExerciseDef): string {
  return `https://www.youtube.com/results?search_query=${encodeURIComponent(def.youtubeQuery)}`;
}
